### PR TITLE
Parse non urls

### LINKED ISSUE #6: Support invalid URLs
If you call `mediaUrlParser('youtu.be/yhRdMTQWhOc')` it will fail to parse it and throw an error. It doesn't throw because it can't find a provider or id but because it's not a valid URL.

I'd like to change the behaviour to parse it anyway and return provider etc.

At the moment radio4000-player will break down if it encounters an URL like "youtu.be/yhRdMTQWhOc". This is because we used to rely on `ytid`.

### PR DESCRIPTION
**Pull request by oskarrough**
Not sure if this is the right way to solve it but it seems to.

What was the ip-check for? Removed it and couldn't see any difference.

Fixes #6

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -31,46 +31,37 @@ const findId = (url, provider) => {
...
 	// from the hostId, find the provider id
 	return providersList[hostId] || 'file'
 }
 
 const extractHostId = (host) => {
 	let els = host.split('.')
-	// is host an ip, aka just numbers
-	if (Number(els.join(''))) {
-		return undefined
-	}
```
Comment (oskarrough) [inline main.js]: what was this for @hugurp ?

File: main.js [hunk 2]
```diff
@@ -31,46 +31,37 @@ const findId = (url, provider) => {
...
 const normalizeUrl = (url) => {
-	let result = new URL(url)
-	// case there is no `http://` in the url
-	if (!result.hostname) {
-		// default to https
-		return `https://${url}`
-	} else {
-		return url
+	if (!url.startsWith('http')) {
+		url = `https://${url}`
```
Comment (oskarrough) [inline main.js:68]: not sure this will work in all cases but tests do pass

File: main.js (hunk 1 above)
Comment (4www) [reply main.js]: "is host an ip, aka just numbers"
https://github.com/internet4000/media-url-parser/blob/master/tests/provider-dictionaries.js#L42
